# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20170829_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_inscricao', models.DateTimeField(blank=True, null=True)),
                ('preco', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='evento',
            name='realizador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pessoasfisicas', to='eventos.PessoaFisica'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.Evento'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='pessoa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.PessoaFisica'),
        ),
    ]
